### ISSUE TITLE
IImage.Resize ObjectDisposedException on Android

### ISSUE THREAD

**Issue by FM1973** [dotnet/System.Graphics#491] opened 2022-11-10 08:21 UTC
Hello.

I know this bug has been addressed in .net 6. (#453 )
After upgrading to .net 7 I got the same problem again.

**Comment by mattleibow** [comment] 2022-11-10 19:40
Duplicate of https://github.com/dotnet/maui/issues/11255

We have merged the repos and this one is now sort of an experimental area.

**Closed as not planned by mattleibow** 2022-11-10 19:40 UTC
